module.exports = {
  answer: 'This is a Answer!',
  cname: '测试名称',
  hex: '#000000',
  name: 'testName',
  nonExistId: -1111,
  password: 'password',
  question: 'This is a problem?',
  shortPasswd: 'pass',
  updateAnswer: '这是一个回答!',
  updateCname: '更新名称',
  updateHex: '#FFFFFF',
  updatePassword: 'updatePd',
  updateQuestion: '这是一个问题？',
  updateName: 'Update Name',
};
