module.exports = {
  answer: 'This is a Answer!',
  cname: '测试名称',
  hex: '#000000',
  name: 'testName',
  nonExistId: -1111,
  password: 'password',
  question: 'This is a problem?',
  shortPasswd: 'pass',
  updateAnswer: '这是一个回答!',
  updateCname: '更新名称',
  updateHex: '#FFFFFF',
  updatePassword: 'updatePd',
  updateQuestion: '这是一个问题？',
  updateName: 'Update Name',
  admin: 'admin',
  adminPasswd: 'admin1234',
  // You should have own token in here. The token just an example.
  token: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MzEsInVzZXIiOiJhZG1pbiIsInJvbGUiOjAsImlhdCI6MTU4NTU4NDIxOH0.xFj3nmvbOjFj0UpzNONm4HHZUc3HxwMKp3hjAVIoV84',
  expiredToken: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjY4LCJ1c2VyIjoiYWRtaW4iLCJyb2xlIjowLCJpYXQiOjE1NzU5NDQ3MzYsImV4cCI6MTU3NTk0NDc0Nn0.TCpk4HMNExB63ZMPrWl3MNM3lKL2X0DazVs8rWMRG1g',
};
